"""
Falsification tests for Track B retirement PR #86.

Generated by falsification audit 2026-05-26.
These tests expose a stale mock target in an existing OOM-mitigation test.
"""

from unittest.mock import patch, Mock
from pathlib import Path
import numpy as np

from views_frames import SpatialLevel, SpatioTemporalIndex


def _make_simple_pf():
    from views_pipeline_core.data.prediction_frame import PredictionFrame

    index = SpatioTemporalIndex(
        time=np.arange(10, dtype=np.int64),
        unit=np.arange(10, dtype=np.int64),
        level=SpatialLevel.PGM,
    )
    return PredictionFrame(np.ones((10, 4), dtype=np.float32), index)


class TestF4StaleMethodPatch:
    """
    F4: test_skip_predictions_delivery_skips_track_b patches to_prediction_df
    but production calls to_arrow_table. The to_prediction_df assertion is a
    tautology — it passes regardless of Track B behavior.

    This test proves the production code never calls to_prediction_df in the
    PF eval path, making the original test's first assertion meaningless.
    """

    def test_to_prediction_df_never_called_in_pf_eval_path_regardless_of_track_b(self):
        """
        Even with skip_predictions_delivery=False (Track B enabled),
        the PF eval path calls to_arrow_table, NOT to_prediction_df.
        This proves the existing test's to_prediction_df mock is a no-op.
        """
        import pyarrow as pa
        from views_pipeline_core.modules.frames.prediction_frame_converter import (
            PredictionFrameConverter,
        )
        from views_pipeline_core.managers.model.model import ForecastingModelManager

        # Import the test helpers from the prediction format test module
        import sys
        sys.path.insert(0, str(Path(__file__).parent / "test_managers"))

        from tests.test_managers.test_model_manager_prediction_format import (
            _make_eval_stub,
        )

        pf = _make_simple_pf()
        manager = _make_eval_stub("prediction_frame")
        manager._config_manager.get_combined_config.return_value[
            "skip_predictions_delivery"
        ] = False
        manager._test_eval_return = {"lr_sb": [pf]}

        dummy_table = pa.table(
            {
                "month_id": [445, 445],
                "priogrid_id": [1, 2],
                "pred_lr_sb": [[1.0, 1.0], [1.0, 1.0]],
            }
        )

        with patch.object(
            PredictionFrameConverter, "to_prediction_df"
        ) as mock_old_method:
            with patch.object(
                PredictionFrameConverter, "to_arrow_table", return_value=dummy_table
            ):
                with patch.object(
                    ForecastingModelManager, "_assert_predictions_in_step_window"
                ):
                    with patch.object(
                        ForecastingModelManager, "_evaluate_prediction_dataframe"
                    ):
                        with patch(
                            "views_pipeline_core.files.utils.handle_single_log_creation"
                        ):
                            with patch("views_pipeline_core.managers.model.mixins._forecast.save_pf"), patch("views_pipeline_core.managers.model.mixins._evaluate.save_pf"):
                                with patch("views_pipeline_core.managers.model.mixins._forecast.load_pf", return_value=Mock()), patch("views_pipeline_core.managers.model.mixins._evaluate.load_pf", return_value=Mock()):
                                    with patch.object(ForecastingModelManager, "_save_combined_eval_parquets"):
                                        manager._execute_model_evaluation()

        # This is the point: to_prediction_df is NEVER called, even when
        # Track B is enabled. The existing test's assertion on this method
        # is meaningless — it would pass in all cases.
        mock_old_method.assert_not_called()