"""
Falsification test stubs for claim: "We have solved the issue on a foundational level"
Generated by /falsify audit on 2026-04-04

These tests document findings from the falsification audit of the
EvaluationManager → NativeEvaluator migration.
"""
from unittest.mock import MagicMock
import sys

sys.modules["wandb"] = MagicMock()
sys.modules["views_evaluation"] = MagicMock()
sys.modules["views_evaluation.evaluation"] = MagicMock()
sys.modules["views_evaluation.evaluation.evaluation_frame"] = MagicMock()
sys.modules["art"] = MagicMock()


def test_falsify_P1_calculate_mean_uses_union_of_keys():
    """
    Probe P1 (Soft Falsification): calculate_mean_evaluation_metrics uses
    only the first item's keys to determine which metrics to average.

    Finding: With dict-based results from EvaluationReport.to_dict(), only
    keys present in the first dict entry are included in the mean. If future
    code changes cause different groups to have different metric sets, later
    groups' extra metrics are silently dropped from the mean calculation.

    With the old dataclass path, vars() always returned all 12 fields
    (including None defaults), so this could never happen.

    Expected: calculate_mean_evaluation_metrics should collect the UNION of
    all keys across all items, not just the first item's keys.

    Currently safe because NativeEvaluator computes identical metrics for
    all groups, but structurally fragile.
    """
    from views_pipeline_core.modules.wandb.utils import calculate_mean_evaluation_metrics

    evaluation_dict = {
        "step01": {"MSE": 0.1},
        "step02": {"MSE": 0.2, "RMSLE": 0.05},
    }

    result = calculate_mean_evaluation_metrics(evaluation_dict)

    # This SHOULD include RMSLE but currently does NOT because only
    # the first item's keys are used to determine metric_names.
    assert "RMSLE" in result, (
        "calculate_mean_evaluation_metrics() silently drops metrics that are "
        "absent from the first item but present in subsequent items. "
        "Use the union of all keys, not just first_item.keys()."
    )
    assert result["RMSLE"] == 0.05, (
        "RMSLE should be the mean of [0.05] = 0.05 (only one valid value)."
    )
