"""
Falsification test stubs for claim: "We have found the biggest risks in this codebase"
Generated by /falsify audit on 2026-04-02

These tests are in TDD RED state -- they FAIL against the current code.
Fix the code to make them pass, then re-run /falsify to verify.
"""
import ast
import sys
from unittest.mock import MagicMock

import pytest
import numpy as np
import pandas as pd

sys.modules["wandb"] = MagicMock()
sys.modules["views_evaluation"] = MagicMock()
sys.modules["views_evaluation.evaluation"] = MagicMock()
sys.modules["views_evaluation.evaluation.evaluation_frame"] = MagicMock()
sys.modules["art"] = MagicMock()


def test_falsify_01_adr008_raise_without_logging():
    """
    Probe 1 (Category B): ADR-008 compliance — raise without preceding logger.error

    Finding: ~10 PipelineException raises in managers/ have no preceding logger.error.
    Locations: model.py:1549, 1941, 2438, 2564, 2605, 3115; ensemble.py:203, 239, 270;
    extractor.py:84; prediction/io.py:106.
    Severity: Hard falsification

    Expected: Every raise of PipelineException (or subclass) is preceded by logger.error
    in the same except block, per ADR-008.
    """
    from pathlib import Path

    src = Path("views_pipeline_core/managers")
    violations = []

    exception_types = {
        "PipelineException", "ModelTrainingException",
        "ModelEvaluationException", "ModelForecastingException",
        "DataFetchException", "ConfigurationException", "ValidationException",
    }

    for py_file in src.rglob("*.py"):
        tree = ast.parse(py_file.read_text())
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler) and node.body:
                has_raise = False
                has_log_error = False
                for stmt in ast.walk(node):
                    if isinstance(stmt, ast.Raise) and stmt.exc:
                        if isinstance(stmt.exc, ast.Call):
                            func = stmt.exc.func
                            name = ""
                            if isinstance(func, ast.Name):
                                name = func.id
                            elif isinstance(func, ast.Attribute):
                                name = func.attr
                            if name in exception_types:
                                has_raise = True
                    if isinstance(stmt, ast.Call):
                        func = stmt.func
                        if isinstance(func, ast.Attribute) and func.attr == "error":
                            if isinstance(func.value, ast.Name) and func.value.id == "logger":
                                has_log_error = True
                if has_raise and not has_log_error:
                    violations.append(f"{py_file.name}:{node.lineno}")

    assert len(violations) == 0, (
        f"ADR-008 violation: {len(violations)} except blocks raise PipelineException "
        f"without preceding logger.error: {violations}"
    )


def test_falsify_02_nan_silent_in_to_tensor():
    """
    Probe 2 (Category C): NaN in _ViewsDataset.to_tensor()

    Finding: Zero NaN checks in _features_to_tensor() or _prediction_to_tensor().
    NaN values in feature columns silently propagate into output tensors.
    Severity: Hard falsification

    Expected: to_tensor() should either raise on NaN input or log a warning.
    Currently it silently produces NaN-containing tensors.
    """
    from views_pipeline_core.data.handlers import _ViewsDataset

    idx = pd.MultiIndex.from_tuples(
        [(1, 500), (1, 501), (2, 500), (2, 501)],
        names=["month_id", "priogrid_id"],
    )
    df = pd.DataFrame(
        {"feature_a": [1.0, np.nan, 3.0, 4.0], "feature_b": [5.0, 6.0, np.nan, 8.0]},
        index=idx,
    )
    ds = _ViewsDataset(df, targets=["feature_a", "feature_b"], broadcast_features=True)

    # to_tensor() should raise ValueError when NaN values are present
    # in feature columns, rather than silently propagating them.
    with pytest.raises(ValueError, match="(?i)nan"):
        ds.to_tensor()


def test_falsify_05_silent_level_override():
    """
    Probe 5 (Category F): ConfigurationManager silent level override

    Finding: If config_hyperparameters has level="cm" and config_deployment has
    level="pgm", the merge silently picks "pgm" with no warning or log.
    CoreConfigSniffer validates the merged value but cannot detect the override.
    Severity: Hard falsification

    Expected: Conflicting safety-critical parameters across config sources should
    produce at least a warning log entry.
    """
    from views_pipeline_core.managers.configuration import ConfigurationManager

    hp = {"level": "cm", "steps": [1, 2, 3]}
    deploy = {"level": "pgm"}

    mgr = ConfigurationManager(
        config_hyperparameters=hp,
        config_deployment=deploy,
    )
    merged = mgr.get_combined_config()

    # The override itself is expected (deployment > hyperparameters).
    # What is NOT expected is the SILENCE of the override.
    # This test asserts that when two sources disagree on 'level',
    # at least a warning is produced.
    # Currently: no warning, no log, no trace.
    assert merged["level"] == "pgm", "Priority merge should pick deployment"

    # TODO: When conflict detection is added, verify a warning was logged.
    # For now, this test documents the gap:
    assert False, (
        "ConfigurationManager silently overrides safety-critical 'level' parameter "
        "from 'cm' (hyperparameters) to 'pgm' (deployment) with no warning. "
        "A conflict between config sources for level/run_type should log a WARNING."
    )


def test_falsify_06_reconciliation_max_workers_ignored():
    """
    Probe 6 (Category E): ReconciliationModule max_workers parameter ignored

    Finding: reconciliation.py computes num_of_workers from max_workers parameter,
    logs it, then passes max_workers=None to ProcessPoolExecutor(), ignoring the
    computed value entirely.
    Severity: Hard falsification

    Expected: ProcessPoolExecutor receives the computed max_workers value.
    """
    from pathlib import Path
    import ast

    src = Path("views_pipeline_core/modules/reconciliation/reconciliation.py")
    tree = ast.parse(src.read_text())

    # Find the ProcessPoolExecutor call and check its max_workers argument
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Attribute) and func.attr == "ProcessPoolExecutor":
                for kw in node.keywords:
                    if kw.arg == "max_workers":
                        # If it's a Name node referencing the computed variable, PASS
                        if isinstance(kw.value, ast.Name) and kw.value.id == "num_of_workers":
                            return  # Fixed!
                        # If it's None constant, FAIL
                        if isinstance(kw.value, ast.Constant) and kw.value.value is None:
                            assert False, (
                                "ProcessPoolExecutor(max_workers=None) ignores the computed "
                                "num_of_workers variable. The max_workers parameter is inoperative. "
                                "CIC guarantee is violated."
                            )

    assert False, "Could not find ProcessPoolExecutor call in reconciliation.py"


def test_falsify_04_evaluation_adapter_silent_truncation():
    """
    Probe 4 (Category B): EvaluationAdapter silent truncation on sparse actuals

    Finding: When actuals DataFrame partially covers the prediction window (e.g.,
    actuals has months 500-502 but predictions cover months 500-511), the adapter
    silently produces a truncated EvaluationFrame (3 rows instead of 12) with no
    warning. Warning is logged ONLY when zero overlap exists.
    Severity: Soft falsification

    Expected: When actuals cover less than 50% of the prediction window, at minimum
    a warning should be logged indicating partial evaluation.
    """
    # TODO: Implement when EvaluationAdapter can be tested without views_evaluation mock
    # The test should:
    # 1. Create actuals with months 500-502
    # 2. Create predictions with months 500-511
    # 3. Call from_dataframes()
    # 4. Assert that a warning is logged about partial coverage
    assert False, (
        "EvaluationAdapter.from_dataframes() silently truncates when actuals "
        "partially cover the prediction window. No warning is logged unless "
        "coverage is exactly zero. Partial evaluation (e.g., 3/12 months) "
        "produces truncated metrics with no indication of incompleteness."
    )
