"""Falsification stub — ensemble-time deprecation check reads stale logs.

Generated by /falsify (2026-07-26) on the ADR-017 guard paragraph.
VERDICT: FALSIFIED (1 hard) — the guard's deprecated-constituent rule is NOT
redundant with the config sniffer: it is the ONLY deprecation check at ensemble
time, and it reads the constituent's log snapshot from artifact-generation time,
so a config deprecated AFTER artifacts were generated is silently missed.

This stub fails BY DESIGN until ensemble-time validation consults current
constituent status (or ADR-017's delivery-boundary coherence replaces the guard).
Run with RUN_GUARD_COHERENCE=1 (skipped otherwise).
"""
import os
import tempfile
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    not os.environ.get("RUN_GUARD_COHERENCE"),
    reason="End-state stub for ensemble-time deprecation coherence; RUN_GUARD_COHERENCE=1",
)


def test_ensemble_time_validation_sees_current_constituent_status():
    """A constituent deprecated after artifact generation must not pass.

    Today: the guard reads the LOG (stale 'shadow'), never the live config →
    returns True. Flips when validation consults current status.
    """
    from views_pipeline_core.modules.validation.ensemble.check import (
        validate_ensemble_model_deployment_status,
    )

    d = Path(tempfile.mkdtemp())
    (d / "calibration_log.txt").write_text(
        "Single Model Name: stale_member\n"
        "Deployment Status: shadow\n"  # log written when the model was shadow
        "Single Model Timestamp: 20260101_000000\n"
        "Data Generation Timestamp: 20260101_000000\n"
        "Data Fetch Timestamp: 20260101_000000\n"
    )
    # The constituent's CURRENT config says deprecated — the guard has no way
    # to know (it never reads configs). This assertion encodes the invariant
    # ensemble-time validation SHOULD hold.
    current_config_status = "deprecated"
    passed = validate_ensemble_model_deployment_status(d, "calibration", "deployed")
    assert not (passed and current_config_status == "deprecated"), (
        "Ensemble-time validation passed a constituent whose current config is "
        "deprecated (stale log said 'shadow') — the deprecation check reads "
        "artifact-generation-time logs, not live status."
    )
