"""Falsification stubs — "baseline + hydranet run end-to-end pandas/polars-free."

Generated by /falsify (2026-07-24). VERDICT: FALSIFIED — 4 hard.

The claim describes the post-activation end-state, not the present. These
stubs fail BY DESIGN until the pandas-free chain completes; each names the
work that flips it. Run with RUN_PANDAS_FREE_E2E=1 (skipped otherwise; the
env gate keeps CI honest meanwhile).

- H1 (P1): no model descriptor anywhere declares data_format: feature_frame —
  the frame path is capability-on-paper, exercised by zero real runs.
- H2 (P2): baseline's production seam is pandas — baseline_manager.py:60,125
  read_dataframe(the parquet cache) on both train and predict.
- H3 (P3): hydranet's input path is entirely pandas — zero FeatureFrame
  references; data_fetcher reads the parquet cache (their #157, open).
- H4 (P5): RESOLVED by #302 (epic #300) and PROMOTED to a permanent CI test:
  tests/test_managers/test_evaluation_stage.py::TestFrameNativeActuals::
  test_frame_evaluate_is_pandas_free (frame-context evaluate with
  read_dataframe patched-to-explode + a prepare_actuals_df tripwire).
Observation (P6): polars is data-path-clean for engine runs (sole importer:
legacy aggregator) but still gets process-loaded via manager import chains.
"""
import os
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    not os.environ.get("RUN_PANDAS_FREE_E2E"),
    reason="End-state stubs for the pandas-free engine chain; enable with RUN_PANDAS_FREE_E2E=1",
)

PLATFORM = Path(__file__).resolve().parents[2]


def _repo(name: str) -> Path:
    path = PLATFORM / name
    if not path.is_dir():
        pytest.skip(f"{name} checkout not present at {path}")
    return path


def test_h1_some_production_model_declares_feature_frame():
    """Flips when a real model opts in (post #266/views-hydranet#157, C-214 lifted)."""
    hits = []
    for repo in ("views-models", "views-hydranet", "views-baseline"):
        root = PLATFORM / repo
        if not root.is_dir():
            continue
        for cfg in root.rglob("config_queryset.py"):
            if ".venv" in cfg.parts:
                continue
            if "feature_frame" in cfg.read_text(errors="ignore"):
                hits.append(cfg)
    assert hits, (
        "No model descriptor anywhere declares data_format: feature_frame — "
        "the frame path is exercised by zero production runs."
    )


def test_h2_baseline_manager_hand_off_is_frame_native():
    """Flips when baseline's manager consumes the frame cache (#266)."""
    src = (_repo("views-baseline") / "views_baseline/manager/baseline_manager.py").read_text()
    assert "read_dataframe" not in src, (
        "baseline_manager still reads the pandas parquet cache "
        "(read_dataframe at the train and predict seams)."
    )
    assert "_get_cached_frame_path" in src or "FeatureFrame" in src


def test_h3_hydranet_input_consumes_feature_frames():
    """Flips when views-hydranet#157 lands."""
    root = _repo("views-hydranet") / "views_hydranet"
    hits = [
        p for p in root.rglob("*.py")
        if "FeatureFrame" in p.read_text(errors="ignore")
    ]
    assert hits, (
        "Zero FeatureFrame references in views_hydranet — the input path is "
        "entirely pandas (data_fetcher reads the parquet cache)."
    )

