"""Falsification regression guards — multi-target prediction overwrite bugfix.

Generated by falsification audit 2026-05-06.
Each test enforces a documentation contract that was missing before the fix.
"""
import inspect


class TestDocstringContractCompleteness:
    """P2a: save_predictions() docstring must document all parameters."""

    def test_save_predictions_docstring_documents_target_identifier(self):
        """The docstring must list target_identifier in the Args section.

        Falsification: target_identifier is in the signature (line 55) but
        missing from the docstring Args block (lines 58-68). A maintainer
        reading the docstring would not know the parameter exists.
        """
        from views_pipeline_core.managers.prediction.io import PredictionIOManager

        doc = inspect.getdoc(PredictionIOManager.save_predictions)
        assert doc is not None, "save_predictions has no docstring"
        assert "target_identifier" in doc, (
            "save_predictions() docstring does not mention target_identifier. "
            "The parameter is in the signature but undocumented."
        )


class TestCICGuaranteesFilenameUniqueness:
    """P2b: ForecastingStage CIC must guarantee per-target filename uniqueness."""

    def test_forecasting_stage_cic_mentions_filename_differentiation(self):
        """The CIC guarantee for per-target saving must specify that filenames
        are differentiated by target_identifier to prevent collisions.

        Falsification: CIC line 42-44 says 'each target's PredictionFrame is
        passed directly to every saver' but does not mention that the filename
        (via metadata) must be unique per target. A maintainer could construct
        PredictionMetadata with identical filenames for different targets and
        believe they're contract-compliant.
        """
        from pathlib import Path

        cic_path = Path(__file__).resolve().parents[1] / "documentation" / "CICs" / "ForecastingStage.md"
        content = cic_path.read_text()
        assert "target_identifier" in content or "unique filename" in content.lower() or "filename differentiation" in content.lower(), (
            "ForecastingStage CIC does not document that per-target filenames "
            "must be unique. The guarantee at line 42-44 is incomplete."
        )
