"""Falsification stubs — #161 Option A design (`get_feature_frame` + five conditions).

Generated by /falsify on the claim: "to the extent practical, advisable, and
WET-before-DRY-respecting, Option A adheres to SOLID + the component principles."

VERDICT: CONTESTED — 2 soft falsifications, no hard ones.

- P1: conditions 1+2 contradict as stated — the shared prologue (get_data:1544-1551)
  MUTATES loader state, while condition 1 demands a free-standing module function.
  Resolution pinned here: the prologue must become value-returning, and the frame
  function must receive explicit values, never the loader instance.
- P2: Option A leaves the frame path UNCALLED — the sole production caller
  (ModelManager._execute_data_fetching, model.py:1146) invokes get_data
  unconditionally. The df-vs-ff mode is displaced to ModelManager, not eliminated;
  the dispatch decision must be made explicitly (and visibly) in #161/#266.

Run with RUN_161_DESIGN=1 (skipped otherwise — these fail BY DESIGN until the
#161 implementation resolves them; the env gate keeps CI honest meanwhile).
"""
import inspect
import os

import pytest

pytestmark = pytest.mark.skipif(
    not os.environ.get("RUN_161_DESIGN"),
    reason="Design-falsification stubs for #161; enable with RUN_161_DESIGN=1",
)


def test_p1_frame_path_function_is_loader_free():
    """The frame-path module function must not take the ViewsDataLoader instance.

    Condition 1 (free-standing module function) is only real if the function's
    signature carries explicit values (partition bounds, source, cache dir) —
    not `self`/`loader`. Passing the loader would silently recreate the
    god-class coupling that condition 1 exists to prevent (P1).
    """
    from views_pipeline_core.modules.dataloaders import feature_frame_path  # not yet written

    fns = [
        obj for name, obj in vars(feature_frame_path).items()
        if callable(obj) and not name.startswith("_")
    ]
    assert fns, "feature_frame_path exposes no public function"
    for fn in fns:
        params = set(inspect.signature(fn).parameters)
        assert not params & {"self", "loader", "data_loader"}, (
            f"{fn.__name__} takes the loader instance — P1 regression: "
            f"the prologue must be value-returning, the function loader-free."
        )


def test_p2_manager_dispatch_to_frame_path_is_explicit():
    """The df-vs-ff choice must be visible at the single production choke point.

    Option A does not eliminate the mode decision — it moves it to
    ModelManager._execute_data_fetching (model.py:1146). Once the frame path is
    activated (#266), that method must contain an explicit, greppable dispatch
    to get_feature_frame; until then this stub fails, keeping the displaced
    decision on the books (P2).
    """
    from views_pipeline_core.managers.model.model import ModelManager

    src = inspect.getsource(ModelManager._execute_data_fetching)
    assert "get_feature_frame" in src, (
        "ModelManager._execute_data_fetching has no dispatch to the frame path — "
        "the displaced mode decision (P2) is still unanswered."
    )
